import { OompaLoompa } from "./declarations";

export const OOMPALOOMPAS: OompaLoompa[] = [
  {
    first_name: "Jarred",
    last_name: "Puleque",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/5.jpg",
    profession: "Developer",
    id: "176",
  },
  {
    first_name: "Liva",
    last_name: "Barry",
    gender: "F",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/6.jpg",
    profession: "Metalworker",
    id: "177",
  },
  {
    first_name: "Kaiser",
    last_name: "Gass",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/7.jpg",
    profession: "Brewer",
    id: "178",
  },
  {
    first_name: "Albert",
    last_name: "Bodycote",
    gender: "F",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/8.jpg",
    profession: "Medic",
    id: "179",
  },
  {
    first_name: "Neysa",
    last_name: "Stendall",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/0.jpg",
    profession: "Developer",
    id: "180",
  },
  {
    first_name: "Oralle",
    last_name: "Lapthorne",
    gender: "F",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/1.jpg",
    profession: "Developer",
    id: "181",
  },
  {
    first_name: "Jone",
    last_name: "Physic",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/2.jpg",
    profession: "Metalworker",
    id: "182",
  },
  {
    first_name: "Seline",
    last_name: "Goulder",
    gender: "F",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/3.jpg",
    profession: "Gemcutter",
    id: "183",
  },
  {
    first_name: "Reuben",
    last_name: "Rodge",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/4.jpg",
    profession: "Medic",
    id: "184",
  },
  {
    first_name: "Lindsey",
    last_name: "Bucky",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/5.jpg",
    profession: "Developer",
    id: "185",
  },
  {
    first_name: "Natale",
    last_name: "Eteen",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/6.jpg",
    profession: "Metalworker",
    id: "186",
  },
  {
    first_name: "Nathaniel",
    last_name: "Dionisi",
    gender: "F",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/7.jpg",
    profession: "Brewer",
    id: "187",
  },
  {
    first_name: "Ramsey",
    last_name: "Roony",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/8.jpg",
    profession: "Medic",
    id: "188",
  },
  {
    first_name: "Gabriele",
    last_name: "Ketteridge",
    gender: "F",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/0.jpg",
    profession: "Developer",
    id: "189",
  },
  {
    first_name: "Pauli",
    last_name: "Poland",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/1.jpg",
    profession: "Developer",
    id: "190",
  },
  {
    first_name: "Norbert",
    last_name: "Kinnard",
    gender: "F",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/2.jpg",
    profession: "Metalworker",
    id: "191",
  },
  {
    first_name: "Bertrando",
    last_name: "Langfield",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/3.jpg",
    profession: "Gemcutter",
    id: "192",
  },
  {
    first_name: "Cary",
    last_name: "Behrens",
    gender: "F",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/4.jpg",
    profession: "Medic",
    id: "193",
  },
  {
    first_name: "Ray",
    last_name: "Itzakson",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/5.jpg",
    profession: "Developer",
    id: "194",
  },
  {
    first_name: "Lindsy",
    last_name: "Jackson",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/6.jpg",
    profession: "Metalworker",
    id: "195",
  },
  {
    first_name: "Rosa",
    last_name: "Sartain",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/7.jpg",
    profession: "Brewer",
    id: "196",
  },
  {
    first_name: "Stevana",
    last_name: "Doust",
    gender: "F",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/8.jpg",
    profession: "Medic",
    id: "197",
  },
  {
    first_name: "Kendell",
    last_name: "Greaterex",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/0.jpg",
    profession: "Developer",
    id: "198",
  },
  {
    first_name: "Beverly",
    last_name: "Giacomucci",
    gender: "F",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/1.jpg",
    profession: "Developer",
    id: "199",
  },
  {
    first_name: "Danell",
    last_name: "Olivier",
    gender: "M",
    image: "https://s3.eu-central-1.amazonaws.com/napptilus/level-test/2.jpg",
    profession: "Metalworker",
    id: "200",
  },
];
